package main

import "edwingarcia.dev/github/jhunterscore/pkg/models"

// Mock data for Offer struct
var offers = []models.Offer{
	{
		Id:           1,
		Title:        "Desarrollador de software",
		Role:         "Desarrollador",
		Company:      "Tech Solutions",
		Description:  "Desarrollo de aplicaciones web y móviles.",
		Requirements: []string{"Experiencia en Go", "Conocimientos en HTML, CSS, JavaScript"},
		Contract:     "trabajo",
		Location:     "Managua, Nicaragua",
		Salary:       "C$50,000",
		Benefits:     []string{"Seguro médico", "Bonos anuales"},
		ContactInfo:  "info@techsolutions.com",
		PublishedAt:  "2023-11-24",
		IsPublished:  true,
	},
	{
		Id:           2,
		Title:        "Diseñador UI/UX",
		Role:         "Diseñador",
		Company:      "Creativos Nica",
		Description:  "Diseño de interfaces de usuario y experiencia de usuario.",
		Requirements: []string{"Experiencia en diseño UI/UX", "Conocimientos en herramientas de diseño"},
		Contract:     "trabajo",
		Location:     "Managua, Nicaragua",
		Salary:       "C$45,000",
		Benefits:     []string{"Seguro médico", "Horario flexible"},
		ContactInfo:  "info@creativosnica.com",
		PublishedAt:  "2023-11-25",
		IsPublished:  true,
	},
	{
		Id:           3,
		Title:        "Especialista en Marketing Digital",
		Role:         "Marketing",
		Company:      "Marketeros Digitales",
		Description:  "Estrategias de marketing digital y gestión de redes sociales.",
		Requirements: []string{"Experiencia en marketing digital", "Conocimientos en SEO y SEM"},
		Contract:     "pasanti",
		Location:     "León, Nicaragua",
		Salary:       "C$30,000",
		Benefits:     []string{"Oportunidad de crecimiento", "Aprendizaje continuo"},
		ContactInfo:  "info@marketerosdigitales.com",
		PublishedAt:  "2023-11-26",
		IsPublished:  true,
	},
	{
		Id:           4,
		Title:        "Analista de Datos",
		Role:         "Analista",
		Company:      "Data Insights",
		Description:  "Análisis de datos y generación de informes para la toma de decisiones.",
		Requirements: []string{"Experiencia en análisis de datos", "Conocimientos en SQL y Python"},
		Contract:     "trabajo",
		Location:     "Managua, Nicaragua",
		Salary:       "C$55,000",
		Benefits:     []string{"Oportunidades de capacitación", "Seguro de vida"},
		ContactInfo:  "info@datainsights.com",
		PublishedAt:  "2023-11-30",
		IsPublished:  true,
	},
	{
		Id:           5,
		Title:        "Ingeniero de Redes",
		Role:         "Ingeniero",
		Company:      "Redes Seguras",
		Description:  "Diseño, implementación y mantenimiento de redes informáticas.",
		Requirements: []string{"Experiencia en redes", "Certificación CCNA"},
		Contract:     "trabajo",
		Location:     "León, Nicaragua",
		Salary:       "C$48,000",
		Benefits:     []string{"Bonos por desempeño", "Plan de jubilación"},
		ContactInfo:  "info@redesseguras.com",
		PublishedAt:  "2023-12-01",
		IsPublished:  true,
	},
	{
		Id:           6,
		Title:        "Asistente Administrativo",
		Role:         "Asistente",
		Company:      "Admin Solutions",
		Description:  "Apoyo administrativo y gestión de documentos.",
		Requirements: []string{"Conocimientos de Microsoft Office", "Experiencia administrativa"},
		Contract:     "pasanti",
		Location:     "Managua, Nicaragua",
		Salary:       "C$25,000",
		Benefits:     []string{"Oportunidades de aprendizaje", "Flexibilidad horaria"},
		ContactInfo:  "info@adminsolutions.com",
		PublishedAt:  "2023-12-02",
		IsPublished:  true,
	},
	{
		Id:           7,
		Title:        "Desarrollador Frontend",
		Role:         "Desarrollador",
		Company:      "Frontend Tech",
		Description:  "Desarrollo de interfaces de usuario para aplicaciones web.",
		Requirements: []string{"Experiencia en desarrollo frontend", "Conocimientos en React"},
		Contract:     "trabajo",
		Location:     "Managua, Nicaragua",
		Salary:       "C$52,000",
		Benefits:     []string{"Seguro médico", "Días de vacaciones pagados"},
		ContactInfo:  "info@frontendtech.com",
		PublishedAt:  "2023-12-03",
		IsPublished:  true,
	},
	{
		Id:           8,
		Title:        "Coordinador de Recursos Humanos",
		Role:         "Recursos Humanos",
		Company:      "HR Solutions",
		Description:  "Gestión de procesos de recursos humanos y relaciones laborales.",
		Requirements: []string{"Experiencia en gestión de recursos humanos", "Conocimientos legales laborales"},
		Contract:     "trabajo",
		Location:     "Managua, Nicaragua",
		Salary:       "C$60,000",
		Benefits:     []string{"Plan de salud integral", "Bonos por desempeño"},
		ContactInfo:  "info@hrsolutions.com",
		PublishedAt:  "2023-12-04",
		IsPublished:  true,
	},
}

// Add more mock data as needed
// ...

var resources = []models.Resource{
	{
		Id:          1,
		Title:       "Crea tu CV",
		Author:      "Carlos Lopez",
		Summary:     "Aprende a crear tu CV.",
		Content:     "# Que es un CV?\n\nUn CV es un documento que sirve para presentar tus habilidades, experiencia y conocimientos a un empleador.",
		PublishedAt: "2023-11-24",
		IsPublished: true,
	},
	{
		Id:          2,
		Title:       "Guía de Búsqueda de Empleo",
		Author:      "Edwin Garcia",
		Summary:     "Consejos prácticos para la búsqueda efectiva de empleo.",
		Content:     "## Guía de Búsqueda de Empleo\n\n### Resumen\nConsejos prácticos para la búsqueda efectiva de empleo.\n\n### Contenido\nIncluye estrategias para crear un currículum destacado y cómo destacar en entrevistas.",
		PublishedAt: "2023-11-25",
		IsPublished: true,
	},
	{
		Id:          3,
		Title:       "Preparación para Entrevistas Técnicas",
		Author:      "Kenroy Norori",
		Summary:     "Cómo prepararse para entrevistas técnicas en la industria de la tecnología.",
		Content:     "## Preparación para Entrevistas Técnicas\n\n### Resumen\nCómo prepararse para entrevistas técnicas en la industria de la tecnología.\n\n### Contenido\nIncluye preguntas frecuentes y ejemplos de ejercicios prácticos.",
		PublishedAt: "2023-11-26",
		IsPublished: true,
	},
	{
		Id:          4,
		Title:       "Conceptos Básicos del Trabajo Remoto",
		Author:      "Enmanuel Olivas",
		Summary:     "Entender los fundamentos del trabajo remoto y cómo adaptarse a este estilo de trabajo.",
		Content:     "## Conceptos Básicos del Trabajo Remoto\n\n### Resumen\nEntender los fundamentos del trabajo remoto y cómo adaptarse a este estilo de trabajo.\n\n### Contenido\nIncluye mejores prácticas para la comunicación y productividad en entornos remotos.",
		PublishedAt: "2023-11-27",
		IsPublished: true,
	},
	{
		Id:          5,
		Title:       "Desarrollo Profesional Continuo",
		Author:      "Ivan Castillo",
		Summary:     "Cómo planificar y ejecutar un plan de desarrollo profesional a lo largo de tu carrera.",
		Content:     "## Desarrollo Profesional Continuo\n\n### Resumen\nCómo planificar y ejecutar un plan de desarrollo profesional a lo largo de tu carrera.\n\n### Contenido\nIncluye consejos para identificar oportunidades de aprendizaje y crecimiento.",
		PublishedAt: "2023-11-28",
		IsPublished: true,
	},
	{
		Id:          6,
		Title:       "Estrategias para Negociar Salarios",
		Author:      "Edwin Garcia",
		Summary:     "Consejos prácticos para negociar un salario justo durante el proceso de contratación.",
		Content:     "## Estrategias para Negociar Salarios\n\n### Resumen\nConsejos prácticos para negociar un salario justo durante el proceso de contratación.\n\n### Contenido\nIncluye ejemplos de situaciones de negociación y cómo abordarlas.",
		PublishedAt: "2023-11-29",
		IsPublished: true,
	},
}
